version: '2'

volumes:
  postgres_data_dev: {}
  postgres_backup_dev: {}

services:
  postgres:
    build: ./compose/postgres
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - postgres_backup_dev:/backups
    environment:
      - POSTGRES_USER=test_project

  sails:
    build:
      context: .
      dockerfile: ./compose/sails/Dockerfile
    command: /start-dev.sh
    depends_on:
      - postgres
      - redis 
    environment:
      - POSTGRES_USER=test_project
      - USE_DOCKER=yes
      - REDIS_HOST=redis 
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    links:
      - postgres
      - redis 

  redis:
    image: redis
    ports:
    - "6379:6379"
    restart: always
